-- MySQL Script generated by MySQL Workbench
-- Sun Jul 31 19:17:56 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `code` VARCHAR(2) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country_code` VARCHAR(2) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_country1_idx` (`country_code` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_customer_country1`
    FOREIGN KEY (`country_code`)
    REFERENCES `mydb`.`country` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`airport` (
  `iata_code` VARCHAR(3) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `country_code` VARCHAR(2) NOT NULL,
  INDEX `fk_airport_country1_idx` (`country_code` ASC),
  PRIMARY KEY (`iata_code`),
  CONSTRAINT `fk_airport_country1`
    FOREIGN KEY (`country_code`)
    REFERENCES `mydb`.`country` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`route` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `origin_airport_iata_code` VARCHAR(3) NOT NULL,
  `dest_airport_iata_code` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_direction_airport1_idx` (`origin_airport_iata_code` ASC),
  INDEX `fk_direction_airport2_idx` (`dest_airport_iata_code` ASC),
  CONSTRAINT `fk_direction_airport1`
    FOREIGN KEY (`origin_airport_iata_code`)
    REFERENCES `mydb`.`airport` (`iata_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direction_airport2`
    FOREIGN KEY (`dest_airport_iata_code`)
    REFERENCES `mydb`.`airport` (`iata_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `route_id` INT NOT NULL,
  `departure_time_gmt` TIMESTAMP NOT NULL,
  `arrival_time_gmt` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_schedule_direction1_idx` (`route_id` ASC),
  CONSTRAINT `fk_schedule_direction1`
    FOREIGN KEY (`route_id`)
    REFERENCES `mydb`.`route` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`flight` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `schedule_id` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_flight_schedule1_idx` (`schedule_id` ASC),
  CONSTRAINT `fk_flight_schedule1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `mydb`.`schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`travel_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`travel_class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aircraft` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aircraft_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aircraft_class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `aircraft_id` INT NOT NULL,
  `travel_class_id` INT NOT NULL,
  INDEX `fk_travel_class_has_aircraft_aircraft1_idx` (`aircraft_id` ASC),
  INDEX `fk_travel_class_has_aircraft_travel_class1_idx` (`travel_class_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_travel_class_has_aircraft_travel_class1`
    FOREIGN KEY (`travel_class_id`)
    REFERENCES `mydb`.`travel_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_travel_class_has_aircraft_aircraft1`
    FOREIGN KEY (`aircraft_id`)
    REFERENCES `mydb`.`aircraft` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flight_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`flight_class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `flight_id` INT NOT NULL,
  `aircraft_class_id` INT NOT NULL,
  `price_in_cents` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_flight_class_price_flight1_idx` (`flight_id` ASC),
  INDEX `fk_flight_class_price_aircraft_class1_idx` (`aircraft_class_id` ASC),
  CONSTRAINT `fk_flight_class_price_flight1`
    FOREIGN KEY (`flight_id`)
    REFERENCES `mydb`.`flight` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_class_price_aircraft_class1`
    FOREIGN KEY (`aircraft_class_id`)
    REFERENCES `mydb`.`aircraft_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `flight_class_id` INT NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `create_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_booking_customer1_idx` (`customer_id` ASC),
  INDEX `fk_booking_flight_class_price1_idx` (`flight_class_id` ASC),
  CONSTRAINT `fk_booking_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_flight_class_price1`
    FOREIGN KEY (`flight_class_id`)
    REFERENCES `mydb`.`flight_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `booking_id` INT NOT NULL,
  `credit_card_number` VARCHAR(255) NOT NULL,
  `credit_card_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_booking1_idx` (`booking_id` ASC),
  CONSTRAINT `fk_payment_booking1`
    FOREIGN KEY (`booking_id`)
    REFERENCES `mydb`.`booking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
